% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{adjustbox}
\usepackage{float}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Outer Sorting Baseline Simulation Memo},
  pdfauthor={Philly Evictions Project},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Outer Sorting Baseline Simulation Memo}
\author{Philly Evictions Project}
\date{2026-03-09}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section{Overview}\label{overview}

This memo summarizes the baseline outer sorting simulation currently
implemented in \texttt{r/simulate-outer-sorting.R} and the associated
first-pass calibration setup in \texttt{r/calibrate-outer-sorting.R}.

The baseline normalization is:

\[
\bar\delta_b = s_b\delta_H + (1 - s_b)\delta_L,
\qquad
\bar f_b = \exp\!\left(a_F + b_{F\theta}\mathbf{1}\{\theta_b = B\} + b_{F\delta}\bar\delta_b\right),
\qquad
x_b \equiv \bar f_b,
\qquad
s_b^\star(\xi) = \Lambda(\xi + \Delta \alpha \bar f_b + \eta_{n(b)}).
\]

The filing block maps building composition into expected filings through
average tenant default risk using a single log-rate equation. The
complaint-composition channel is restricted to bad landlords, and
maintenance is parameterized directly in per-unit levels through
\texttt{m0}. The sorting signal is still the expected filing rate, and
the simulation iterates on expected maintenance, complaint, and filing
rates until the building composition vector is a fixed point under the
citywide mass constraint.

\section{Simulation Setup}\label{simulation-setup}

The baseline parameterization fixes the citywide high-risk share at
\(\mu = 0.30\), interpretable as a rough renter-poverty /
precarious-tenant share. The tenant default anchors are set to
\(\delta_L = 0.01\) and \(\delta_H = 0.10\), implying an average
anchored default probability of roughly 0.037.

The baseline filing block uses average default risk,
\(\bar\delta_b = s_b\delta_H + (1-s_b)\delta_L\), inside a single
log-rate Poisson structure. Complaints depend on composition only
through the interaction
\texttt{s\_b\ ×\ 1\{\textbackslash{}theta\_b\ =\ B\}}, reflecting the
current theoretical restriction that complaint suppression operates only
for bad landlords. The maintenance block is parameterized with
\texttt{m0}, the baseline expected maintenance rate per unit. Both the
maintenance and complaint equations now also include exogenous
old-building and new-building indicators derived from empirically
resampled \texttt{year\_built}, so age-related upkeep differences do not
have to be absorbed entirely by landlord type or complaint-response
coefficients. The sorting block still includes a neighborhood shifter
\(\eta_{n(b)}\), so the model does not need to push all low-income-share
dispersion through the filing process. On the empirical side, the
current composition proxy is a building-level InfoUSA low-income share
based on \texttt{find\_div\_1000} and a fixed income threshold.
Simulated building units and year-built observables are drawn jointly by
empirical resampling from the observed PID-level BLP distribution over
2011-2019, rather than from the old stylized unit bins.

The realized simulation panel is now annualized over the configured
simulation window rather than being a one-shot annual draw. For each
simulated building, the code computes active exposure years from
\texttt{year\_built}, draws total counts over those unit-years from
stationary Poisson processes, and divides back by exposure years. That
makes the simulated \texttt{M}, \texttt{C}, \texttt{F},
\texttt{m\_rate}, \texttt{c\_rate}, and \texttt{f\_rate} directly
comparable to the empirical PID-level annualized objects built from
\texttt{2011}-\texttt{2019}.

One implementation detail is worth being explicit about: after the final
exact citywide-mass projection of \texttt{s}, the simulator refreshes
the expected maintenance, complaint, and filing rates once at that
projected composition rather than fully re-solving the
maintenance/complaint subsystem conditional on the projected \texttt{s}.
Under the current tight tolerances, this should be a small numerical
approximation rather than a material change in the reported equilibrium.

\begin{table}
\tiny

\caption{Baseline outer sorting parameters}
\centering
\begin{tabular}[t]{llrll}
\toprule
block & parameter & value & status & note\\
\midrule
Simulation & B & 10000.0000 & Fixed & Number of simulated buildings in the baseline run.\\
Simulation & sim\_year\_from & 2011.0000 & Fixed & First year in the simulation window used to annualize simulated outcomes.\\
Simulation & sim\_year\_to & 2019.0000 & Fixed & Last year in the simulation window used to annualize simulated outcomes.\\
Tenant-side anchors & mu & 0.3000 & Fixed & Citywide high-risk / precarious tenant share.\\
Tenant-side anchors & delta\_L & 0.0100 & Fixed & Anchored low-risk default probability.\\
Tenant-side anchors & delta\_H & 0.1000 & Fixed & Anchored high-risk default probability.\\
Built environment & p\_bad\_shape1 & 2.0000 & Calibrated & Beta shape parameter for tract bad-type prevalence.\\
Built environment & p\_bad\_shape2 & 6.0000 & Calibrated & Beta shape parameter for tract bad-type prevalence.\\
Building age & old\_bldg\_cutoff\_year & 1940.0000 & Fixed & Observed-building threshold for old-building indicator.\\
Building age & new\_bldg\_cutoff\_year & 2000.0000 & Fixed & Observed-building threshold for new-building indicator.\\
Sorting & Dalph & 6.0000 & Calibrated & Sorting strength in the logistic update.\\
Sorting & sigma\_eta\_sort & 0.6000 & Calibrated & Neighborhood sorting shifter standard deviation.\\
Filing & aF & -3.0000 & Calibrated & Filing log-rate intercept.\\
Filing & bF\_theta & 0.7000 & Calibrated & Bad-type filing shift.\\
Filing & bF\_delta & 1.1000 & Calibrated & Sensitivity of filings to average tenant default risk.\\
Complaints & aC & -2.1000 & Calibrated & Complaint intercept.\\
Complaints & bC\_theta & 0.3500 & Calibrated & Bad-type complaint shift.\\
Complaints & bC\_s\_bad & -0.1000 & Calibrated & Complaint-composition slope for bad landlords only.\\
Complaints & bC\_old & 0.1000 & Calibrated & Complaint shift for older buildings.\\
Complaints & bC\_new & -0.0500 & Calibrated & Complaint shift for newer buildings.\\
Complaints & bC\_M & -0.1000 & Calibrated & Complaint response to maintenance.\\
Maintenance & m0 & 0.1827 & Calibrated & Baseline per-unit maintenance rate.\\
Maintenance & bM\_theta & -0.2000 & Calibrated & Bad-type maintenance shift.\\
Maintenance & bM\_old & 0.1500 & Calibrated & Maintenance shift for older buildings.\\
Maintenance & bM\_new & 0.2500 & Calibrated & Maintenance shift for newer buildings.\\
Maintenance & bM\_C & 0.1200 & Calibrated & Maintenance response to complaint intensity.\\
Numerics & lam & 0.4000 & Calibrated & Damping parameter in the fixed-point iteration.\\
Numerics & tol & 0.0000 & Calibrated & Stopping tolerance on the composition update.\\
Numerics & max\_iter & 300.0000 & Calibrated & Maximum fixed-point iterations.\\
Numerics & high\_filing\_threshold & 0.1500 & Numeric & Absolute filing-rate cutoff for high-filing moments.\\
Simulation & B & 10000.0000 & Numeric & Number of simulated buildings in the baseline run.\\
Simulation & sim\_year\_from & 2011.0000 & Numeric & First year in the simulation window used to annualize simulated outcomes.\\
Simulation & sim\_year\_to & 2019.0000 & Fixed & Last year in the simulation window used to annualize simulated outcomes.\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Unit Exposure}\label{unit-exposure}

\begin{table}

\caption{Empirical vs simulated unit distribution summary}
\centering
\begin{tabular}[t]{lrrrrrrr}
\toprule
sample & n & mean\_units & p50\_units & p90\_units & p95\_units & p99\_units & max\_units\\
\midrule
Empirical PID average annual units & 192043 & 2.0650 & 1 & 2 & 4 & 20 & 715\\
Simulated buildings & 10000 & 2.0328 & 1 & 2 & 4 & 22 & 250\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Empirical Filing-Rate
Check}\label{empirical-filing-rate-check}

\begin{table}

\caption{Empirical filing-rate check}
\centering
\begin{tabular}[t]{llr}
\toprule
sample & statistic & value\\
\midrule
Empirical target panel & mean\_f\_rate (unit-weighted) & 0.0442\\
Empirical target panel & mean\_f\_rate (unweighted) & 0.0435\\
\bottomrule
\end{tabular}
\end{table}

Under the current empirical target construction, the filing-rate target
is about 0.044 on a unit-weighted basis and 0.043 on an unweighted
building basis. If the intended raw-data benchmark is closer to
\texttt{0.06}, that likely reflects a definitional difference in the
empirical target rather than a calibration problem by itself.

\section{Convergence}\label{convergence}

The deterministic fixed-point algorithm converged cleanly in the current
baseline run. The maximum change in the composition vector was below the
configured tolerance, and the final citywide mass residual was
effectively zero.

\begin{table}

\caption{Fixed-point convergence summary}
\centering
\begin{tabular}[t]{ll}
\toprule
metric & value\\
\midrule
Converged & TRUE\\
Iterations & 26\\
Max composition change & 6.34e-07\\
Mass residual before final projection & -9.6e-10\\
Mass residual after final projection & -9.48e-10\\
Final xi & -1.2584\\
Target mu & 0.300\\
Weighted mean s & 0.300\\
\bottomrule
\end{tabular}
\end{table}

The simulation is solving the stationary equilibrium under the exact
citywide mass constraint, so the weighted mean of simulated composition
lines up with the target \(\mu\) by construction.

\section{Resulting Equilibrium}\label{resulting-equilibrium}

The baseline equilibrium implies:

\begin{itemize}
\tightlist
\item
  unit-weighted mean filing, maintenance, and complaint rates of about
  0.065, 0.200, and 0.138 per unit
\item
  substantial zero mass in the annualized outcomes, where zero shares
  are unweighted shares of buildings
\item
  higher group-1 shares and higher filing / complaint intensity in
  bad-type buildings than in good-type buildings
\end{itemize}

\begin{table}

\caption{Equilibrium summary moments}
\centering
\begin{tabular}[t]{lr}
\toprule
moment & value\\
\midrule
Mean filing rate & 0.0646\\
Mean maintenance rate & 0.1997\\
Mean complaint rate & 0.1382\\
Zero filings share & 0.4889\\
Zero maintenance share & 0.1326\\
Zero complaints share & 0.2356\\
Sorting slope on high filing within neighborhood & 0.0201\\
Sorting slope: top filing bin vs low filing bin & 0.0254\\
Complaint on composition & 4.5695\\
Complaint on composition x high filing & -0.2458\\
Maintenance on complaint intensity & -0.2548\\
Residual SD of filing rate after neighborhood FE & 0.0816\\
\bottomrule
\end{tabular}
\end{table}

\subsection{By Landlord Type}\label{by-landlord-type}

\begin{table}

\caption{Equilibrium summary by landlord type}
\centering
\begin{tabular}[t]{lrrrrrrr}
\toprule
theta & mean\_s & mean\_f\_rate & mean\_c\_rate & mean\_m\_rate & zero\_f & zero\_c & zero\_m\\
\midrule
G & 0.2852 & 0.0517 & 0.1273 & 0.2090 & 0.5454 & 0.2516 & 0.1203\\
B & 0.3471 & 0.1057 & 0.1728 & 0.1702 & 0.3169 & 0.1870 & 0.1700\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Outcome Distributions}\label{outcome-distributions}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/rate-histograms-1.pdf}

}

\caption{Distribution of realized filing, complaint, and maintenance
rates across simulated buildings.}

\end{figure}%

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/empirical-vs-sim-rate-histograms-1.pdf}

}

\caption{Empirical vs simulated building-level distributions of filing
and complaint rates per unit.}

\end{figure}%

\subsection{Sorting Pattern}\label{sorting-pattern}

\begin{figure}[H]

{\centering \includegraphics[width=0.92\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/sorting-figure-1.pdf}

}

\caption{Distribution of equilibrium composition shares and realized
filing rates by landlord type.}

\end{figure}%

\subsection{Neighborhood Patterns}\label{neighborhood-patterns}

\begin{table}

\caption{Empirical vs simulated neighborhood distribution summary}
\centering
\begin{tabular}[t]{llrrr}
\toprule
sample & metric & mean & p50 & p90\\
\midrule
Empirical neighborhoods & Neighborhood mean filing rate & 0.0470 & 0.0442 & 0.0892\\
Empirical neighborhoods & Neighborhood mean low-income share & 0.4984 & 0.5075 & 0.9070\\
Simulated neighborhoods & Neighborhood mean filing rate & 0.0652 & 0.0645 & 0.0853\\
Simulated neighborhoods & Neighborhood mean low-income share & 0.3096 & 0.3052 & 0.4838\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/nhood-figures-1.pdf}

}

\caption{Neighborhood-level equilibrium variation in filing rates and
group-1 share, using unit-weighted neighborhood means.}

\end{figure}%

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/nhood-empirical-vs-sim-1.pdf}

}

\caption{Empirical vs simulated neighborhood distributions for
unit-weighted neighborhood mean filing rates and neighborhood mean
low-income shares.}

\end{figure}%

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/nhood-diagnostics-1.pdf}

}

\caption{Neighborhood diagnostic views: ranked neighborhood group-1
shares and neighborhood mean filing rates against neighborhood mean
group-1 shares.}

\end{figure}%

\begin{figure}[H]

{\centering \includegraphics[width=0.95\linewidth,height=\textheight,keepaspectratio]{outer-sorting-baseline_files/figure-pdf/nhood-filing-drivers-1.pdf}

}

\caption{Neighborhood filing-rate variation against neighborhood
bad-type share and by neighborhood size.}

\end{figure}%

\section{First-Pass Calibration
Targets}\label{first-pass-calibration-targets}

The first-pass calibration objective now uses a 16-moment target set:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Three marginal means: filing, maintenance, and complaint rates.
\item
  Three maintenance-intensity moments: the positive-part mean
  maintenance rate and the positive-part 50th and 90th percentiles.
\item
  Four neighborhood-dispersion moments: SD and 90-10 spread of
  neighborhood mean low-income shares and neighborhood mean filing
  rates.
\item
  Two sorting moments: composition on high filing within neighborhood,
  and composition for the top filing bin relative to the low filing bin
  within neighborhood.
\item
  Two complaint-gradient moments: complaints on composition, and
  complaints on composition \(\times\) high filing.
\item
  One maintenance-discipline moment: maintenance counts on the raw
  complaint rate per unit, with neighborhood fixed effects and a unit
  offset.
\item
  One filing-dispersion moment: residual SD of filing rates after
  neighborhood fixed effects.
\end{enumerate}

The zero-filing, zero-complaint, and zero-maintenance shares are still
reported below as diagnostics, but they are no longer targeted directly
in the objective. Once the panel is annualized over multiple years,
those extensive-margin zeros are less informative than the level and
dispersion moments.

The within-neighborhood sorting diagnostics are already in the
calibration outputs: \texttt{sorting\_coef\_high\_filing\_nhood} and
\texttt{sorting\_coef\_high\_bin\_nhood}. Those are the cleanest direct
comparisons for whether the model is over- or under-sorting conditional
on neighborhood fixed effects.

The current calibration target product is
outer\_sorting\_empirical\_moments, so the moment comparison table below
should be read as an empirical fit diagnostic rather than a
self-calibration check.

\begin{table}

\caption{Calibration target vs simulated moments}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
moment & target & simulated & weight & diff\\
\midrule
mean\_f\_rate & 0.0442 & 0.1538 & 10 & -0.1100\\
mean\_m\_rate & 0.0441 & 0.2939 & 10 & -0.2500\\
mean\_c\_rate & 0.0714 & 0.1206 & 10 & -0.0493\\
mean\_m\_rate\_pos & 0.2569 & 0.3255 & 5 & -0.0686\\
m\_rate\_pos\_p50 & 0.1250 & 0.3333 & 5 & -0.2080\\
m\_rate\_pos\_p90 & 0.5556 & 0.5556 & 5 & 0.0000\\
nhood\_mean\_s\_sd & 0.3107 & 0.1197 & 8 & 0.1910\\
nhood\_mean\_s\_p90\_p10 & 0.8409 & 0.3160 & 8 & 0.5250\\
nhood\_mean\_f\_rate\_sd & 0.0387 & 0.0347 & 5 & 0.0039\\
nhood\_mean\_f\_rate\_p90\_p10 & 0.0808 & 0.0880 & 5 & -0.0071\\
sorting\_coef\_high\_filing\_nhood & 0.0659 & 0.1421 & 5 & -0.0763\\
sorting\_coef\_high\_bin\_nhood & 0.0721 & 0.1420 & 5 & -0.0699\\
beta\_ppml\_s & -0.0570 & 0.1149 & 2 & -0.1720\\
beta\_ppml\_s\_x\_high\_filing & -0.1159 & -0.1181 & 2 & 0.0022\\
beta\_maint\_on\_c\_rate & 1.2023 & 0.5117 & 3 & 0.6910\\
filing\_resid\_sd\_nhood\_fe & 0.1261 & 0.1336 & 5 & -0.0075\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Current Calibration Run}\label{current-calibration-run}

\begin{table}

\caption{Calibration run summary}
\centering
\begin{tabular}[t]{ll}
\toprule
metric & value\\
\midrule
Target product & outer\_sorting\_empirical\_moments\\
Convergence code & 1\\
Objective & 5.0489\\
Evaluations & 321\\
\bottomrule
\end{tabular}
\end{table}

The current empirical calibration run did not fully converge in the
optimizer. The fixed-point solver inside each simulation evaluation is
behaving, but the outer optimizer stopped at convergence code 1 with
objective 5.049 after 321 evaluations.

\begin{table}

\caption{Baseline vs calibrated parameters}
\centering
\begin{tabular}[t]{lrrr}
\toprule
parameter & baseline & calibrated & change\\
\midrule
p\_bad\_shape1 & 2.0000 & 2.1643 & 0.1643\\
p\_bad\_shape2 & 6.0000 & 5.9940 & -0.0060\\
Dalph & 6.0000 & 10.0609 & 4.0609\\
sigma\_eta\_sort & 0.6000 & 0.5278 & -0.0722\\
m0 & 0.1827 & 0.2206 & 0.0379\\
bM\_theta & -0.2000 & -0.0808 & 0.1192\\
bM\_old & 0.1500 & 0.4014 & 0.2514\\
bM\_new & 0.2500 & 0.1385 & -0.1115\\
bM\_C & 0.1200 & 0.3516 & 0.2316\\
aC & -2.1000 & -2.2976 & -0.1976\\
bC\_theta & 0.3500 & 0.1391 & -0.2109\\
bC\_s\_bad & -0.1000 & -0.2883 & -0.1883\\
bC\_old & 0.1000 & 0.3389 & 0.2389\\
bC\_new & -0.0500 & 0.0493 & 0.0993\\
bC\_M & -0.1000 & -0.1068 & -0.0068\\
aF & -3.0000 & -2.2202 & 0.7798\\
bF\_theta & 0.7000 & 0.8215 & 0.1215\\
bF\_delta & 1.1000 & 0.7663 & -0.3337\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{Largest calibration moment misses}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
moment & target & simulated & diff & weighted\_sq\_error\\
\midrule
nhood\_mean\_s\_p90\_p10 & 0.8409 & 0.3160 & 0.5249 & 2.2040\\
beta\_maint\_on\_c\_rate & 1.2023 & 0.5117 & 0.6907 & 1.4310\\
mean\_m\_rate & 0.0441 & 0.2939 & -0.2498 & 0.6241\\
nhood\_mean\_s\_sd & 0.3107 & 0.1197 & 0.1909 & 0.2917\\
m\_rate\_pos\_p50 & 0.1250 & 0.3333 & -0.2083 & 0.2170\\
mean\_f\_rate & 0.0442 & 0.1538 & -0.1095 & 0.1200\\
beta\_ppml\_s & -0.0570 & 0.1149 & -0.1718 & 0.0591\\
sorting\_coef\_high\_filing\_nhood & 0.0659 & 0.1421 & -0.0763 & 0.0291\\
\bottomrule
\end{tabular}
\end{table}

The largest misses are informative. In the current run, the model still
overpredicts filing and maintenance rates, produces too little zero
mass, and generates much stronger sorting gradients than the empirical
target. The maintenance-discipline moment is also much smaller in the
simulated equilibrium than in the data target.

\section{Current Interpretation}\label{current-interpretation}

The baseline equilibrium does the basic qualitative work the model is
supposed to do: bad-type buildings end up with higher filing rates and
higher group-1 shares, while maintenance is lower on average in those
buildings and complaints are higher. The citywide mass constraint is
satisfied tightly and the deterministic fixed point converges quickly.

The empirical calibration results suggest that the current baseline is
directionally coherent but still too aggressive relative to the data.
The main gaps are in outcome levels, zero mass, sorting strength, and
the complaint-maintenance discipline link.

The next substantive question is whether these misses come mostly from
the empirical target construction, from the InfoUSA low-income-share
proxy for composition, or from the structural tightness of the filing,
complaint, and maintenance blocks themselves.




\end{document}
